from module.assignment5 import Heap


heap = Heap()
heap.insert(3)
heap.insert(2)
heap.insert(4)
heap.insert(5)
print(heap.arr)
heap.insert(1)
print(heap.arr)
print(heap.peek())
heap.heapPop()
print(heap.arr)
heap.heapPop()
print(heap.arr)
heap.heapPop()
print(heap.arr)
heap.heapPop()
print(heap.arr)
heap.heapPop()
print(heap.arr)


heap = minHeap([5, 4, 3, 2, 1])
heap = minHeap([6, 8, 10, 11, 2])
heap.heapPop()
heap.heapPop()
print(heap.arr)

heap = maxHeap([1, 2, 3, 4, 5])
heap.heapPop()
print(heap.arr)
heap.heapPop()
print(heap.arr)
heap.heapPop()
print(heap.arr)
heap.heapPop()
print(heap.arr)
heap.heapPop()
print(heap.arr)